### ISSUE TITLE
failed to compile caddy2 with cloudflare dns plugin

### ISSUE THREAD

**Issue by NetHeritage** [caddy-dns/cloudflare#14] opened 2020-08-28 12:59 UTC
root@ubuntu-persoonal-cloud:~/go/caddy2# xcaddy build --with github.com/caddy-dn                                                                                                             s/cloudflare
2020/08/28 12:57:57 [INFO] Temporary folder: /tmp/buildenv_2020-08-28-1257.92788                                                                                                             7518
2020/08/28 12:57:57 [INFO] Writing main module: /tmp/buildenv_2020-08-28-1257.92                                                                                                             7887518/main.go
2020/08/28 12:57:57 [INFO] Initializing Go module
2020/08/28 12:57:57 [INFO] exec (timeout=10s): /usr/local/go/bin/go mod init cad                                                                                                             dy
go: creating new go.mod: module caddy
2020/08/28 12:57:57 [INFO] Pinning versions
2020/08/28 12:57:57 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v git                                                                                                             hub.com/caddyserver/caddy/v2
go: github.com/caddyserver/caddy/v2 upgrade => v2.1.1
2020/08/28 12:57:59 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v git                                                                                                             hub.com/caddy-dns/cloudflare
go: github.com/caddy-dns/cloudflare upgrade => v0.0.0-20200811180534-4494da72fa5                                                                                                             6
2020/08/28 12:58:01 [INFO] Build environment ready
2020/08/28 12:58:01 [INFO] Building Caddy
2020/08/28 12:58:01 [INFO] exec (timeout=0s): /usr/local/go/bin/go build -o /roo                                                                                                             t/go/caddy2/caddy -ldflags -w -s -trimpath
# github.com/smallstep/certificates/authority/provisioner
/root/go/pkg/mod/github.com/smallstep/certificates@v0.15.0-rc.1.0.20200506212953                                                                                                             -e855707dc274/authority/provisioner/jwk.go:155:24: assignment mismatch: 3 variab                                                                                                             les but x509util.SplitSANs returns 4 values
/root/go/pkg/mod/github.com/smallstep/certificates@v0.15.0-rc.1.0.20200506212953                                                                                                             -e855707dc274/authority/provisioner/x5c.go:197:24: assignment mismatch: 3 variab                                                                                                             les but x509util.SplitSANs returns 4 values
2020/08/28 12:58:02 [INFO] Cleaning up temporary folder: /tmp/buildenv_2020-08-2                                                                                                             8-1257.927887518

**Comment by mholt** [comment] 2020-08-31 19:15
Duplicate of #11

**Closed by mholt** 2020-08-31 19:15 UTC
