### ISSUE TITLE
Unable to read zone

### ISSUE THREAD

**Issue by rati0nal** [caddy-dns/cloudflare#12] opened 2020-08-13 03:39 UTC
Hello,

I've built Caddy with the dns cloudflare module, but when setup with the DNS challenge, I get the following issue:

`caddy caddy[366]: {"level":"error","ts":1597289488.5149934,"logger":"tls.obtain","msg":"will retry","error":"[subdomain.example.com] Obtain: [subdomain.example.com] solving challenges: presenting for challenge: adding temporary record for zone co.: got error status: HTTP 403: [{Code:0 Message:Actor 'com.cloudflare.api.token.xxxxxxxxxxxxxxxxxxxxxx' requires permission 'com.cloudflare.api.account.zone.read' to list zones}] (ca=https://acme-v02.api.letsencrypt.org/directory)","attempt":1,"retrying_in":60,"elapsed":2.603871005,"max_duration":2592000}`

I've tried all sorts of api token config and finally just made a token with access to all resources, but still getting this error. When Googling I can't find anything referencing the specific "com.cloudflare.api.account.zone.read".

I checked Cloudflares API resources and they note there is a 'Zone.Read' under 'Accounts' but it doesn't appear available in my Cloudflare API settings.

I'm not sure where to go from here?

**Comment by mholt** [comment] 2020-08-17 21:20
Is this still happening with the latest version of Caddy (build from master) + certmagic + libdns/cloudflare?

**Comment by rati0nal** [comment] 2020-08-19 01:57
I'm not very proficient with building like this, but I tried:
```
./xcaddy build \
	--with github.com/caddyserver/certmagic
	--with github.com/caddy-dns/cloudflare

```
Which I did previously but without certmagic. I get the following error:

```
/root/go/pkg/mod/github.com/smallstep/certificates@v0.15.0-rc.1.0.20200506212953-e855707dc274/authority/provisio:155:24: assignment mismatch: 3 variables but x509util.SplitSANs returns 4 values
/root/go/pkg/mod/github.com/smallstep/certificates@v0.15.0-rc.1.0.20200506212953-e855707dc274/authority/provisio:197:24: assignment mismatch: 3 variables but x509util.SplitSANs returns 4 values
```

**Comment by mholt** [comment] 2020-08-31 19:16
See #11 -- solution is there, until caddyserver/caddy v2.2.0 is tagged.

**Comment by NetHeritage** [comment] 2020-09-01 09:07
root@cccc:~/go/caddy2# xcaddy build v2.2.0 --with github.com/caddy-dns/cloudflar                                                                                                             e@latest  --with github.com/caddyserver/forwardproxy=$PWD/forwardproxy
2020/09/01 09:03:49 [INFO] Temporary folder: /tmp/buildenv_2020-09-01-0903.28412                                                                                                             8971
2020/09/01 09:03:49 [INFO] Writing main module: /tmp/buildenv_2020-09-01-0903.28                                                                                                             4128971/main.go
2020/09/01 09:03:49 [INFO] Initializing Go module
2020/09/01 09:03:49 [INFO] exec (timeout=10s): /usr/local/go/bin/go mod init cad                                                                                                             dy
go: creating new go.mod: module caddy
2020/09/01 09:03:49 [INFO] Replace github.com/caddyserver/forwardproxy => /root/                                                                                                             go/caddy2/forwardproxy
2020/09/01 09:03:49 [INFO] exec (timeout=10s): /usr/local/go/bin/go mod edit -re                                                                                                             place github.com/caddyserver/forwardproxy=/root/go/caddy2/forwardproxy
2020/09/01 09:03:49 [INFO] Pinning versions
2020/09/01 09:03:49 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v git                                                                                                             hub.com/caddyserver/caddy/v2@v2.2.0
go get github.com/caddyserver/caddy/v2@v2.2.0: github.com/caddyserver/caddy/v2@v                                                                                                             2.2.0: invalid version: unknown revision v2.2.0
2020/09/01 09:03:51 [FATAL] exit status 1




root@cccc:~/go/caddy2# xcaddy build master --with github.com/caddy-dns/cloudflar                                                                                                             e@latest  --with github.com/caddyserver/forwardproxy=$PWD/forwardproxy
2020/09/01 09:04:26 [INFO] Temporary folder: /tmp/buildenv_2020-09-01-0904.55163                                                                                                             2401
2020/09/01 09:04:26 [INFO] Writing main module: /tmp/buildenv_2020-09-01-0904.55                                                                                                             1632401/main.go
2020/09/01 09:04:26 [INFO] Initializing Go module
2020/09/01 09:04:26 [INFO] exec (timeout=10s): /usr/local/go/bin/go mod init cad                                                                                                             dy
go: creating new go.mod: module caddy
2020/09/01 09:04:26 [INFO] Replace github.com/caddyserver/forwardproxy => /root/                                                                                                             go/caddy2/forwardproxy
2020/09/01 09:04:26 [INFO] exec (timeout=10s): /usr/local/go/bin/go mod edit -re                                                                                                             place github.com/caddyserver/forwardproxy=/root/go/caddy2/forwardproxy
2020/09/01 09:04:26 [INFO] Pinning versions
2020/09/01 09:04:26 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v git                                                                                                             hub.com/caddyserver/caddy/v2@master
go: github.com/caddyserver/caddy/v2 master => v2.2.0-rc.1.0.20200831192326-24f34                                                                                                             780b61f
2020/09/01 09:04:28 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v git                                                                                                             hub.com/caddy-dns/cloudflare@latest
go: github.com/caddy-dns/cloudflare latest => v0.0.0-20200811180534-4494da72fa56
2020/09/01 09:04:28 [INFO] Build environment ready
2020/09/01 09:04:28 [INFO] Building Caddy
2020/09/01 09:04:28 [INFO] exec (timeout=0s): /usr/local/go/bin/go build -o /roo                                                                                                             t/go/caddy2/caddy -ldflags -w -s -trimpath
go: found github.com/caddyserver/forwardproxy in github.com/caddyserver/forwardp                                                                                                             roxy v0.0.0-00010101000000-000000000000
2020/09/01 09:04:34 [INFO] Build complete: caddy
2020/09/01 09:04:34 [INFO] Cleaning up temporary folder: /tmp/buildenv_2020-09-0                                                                                                             1-0904.551632401

**Comment by alexyao2015** [comment] 2020-10-07 05:05
Is there something wrong with this? I am getting a very similar error as above.

`Renew: [xxxxxxxxxxxxxxxxxx.com] solving challenges: presenting for challenge: adding temporary record for zone xxxxxxxxxxxxxxxxxx.com.: got error status: HTTP 403: [{Code:0 Message:Actor 'com.cloudflare.api.token.xxxxxxxxxxxxxxxxxxx' requires permission 'com.cloudflare.api.account.zone.read' to list zones}] (order=https://acme-staging-v02.api.letsencrypt.org/acme/order/14871439/163013089) (ca=https://acme-staging-v02.api.letsencrypt.org/directory)", "attempt": 2, "retrying_in": 120, "elapsed": 61.82477189, "max_duration": 2592000}`

```
FROM caddy:2.2.0-builder AS builder

RUN xcaddy build v2.2.0 \
	--with github.com/caddyserver/certmagic@latest \
    --with github.com/caddy-dns/cloudflare@latest

FROM caddy:2.2.0

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

**Comment by alexyao2015** [comment] 2020-10-07 05:24
I've done some more tests using curl and have determined that it may be related to my usage of a subdomain which results in these issues. 
This will fail
`curl -X GET "https://api.cloudflare.com/client/v4/zones?name=SUBDOMAIN.DOMAIN.COM" -H "Content-Type:application/json" -H "Authorization: Bearer CLOUDFLARE_AUTH_TOKEN"`

However, this passes. 
`curl -X GET "https://api.cloudflare.com/client/v4/zones?name=DOMAIN.COM" -H "Content-Type:application/json" -H "Authorization: Bearer CLOUDFLARE_AUTH_TOKEN"`

Does the plugin send the request in the form of the first request? If it does, I would assume that is what causes it, and it should be listed as a potential bug.

**Comment by alexyao2015** [comment] 2020-10-07 05:59
Sorry about cluttering this issue. My issue here was definitely related to #3 / #13 caused by split brain dns which should have been resolved in caddyserver/caddy#2476. Removing the zone in my dns server resolved the issue, however, I also tried using the new resolvers directive in my caddyfile without any luck.
```
	tls { 
		issuer acme {
			dns cloudflare {env.CLOUDFLARE_AUTH_TOKEN}
			resolvers 8.8.8.8
		}
	}
```

**Comment by mholt** [comment] 2020-10-08 18:29
@alexyao2015 So things are working for you, except if you specify the DNS resolvers in the Caddyfile? Does it adapt to JSON correctly? (run `caddy adapt` and verify output) -- would you be able to dig down and find out where the resolver logic is wrong?

**Comment by alexyao2015** [comment] 2020-10-08 21:03
This is what I get from caddy adapt, so it definitely does seem to be working. I'll do some further testing to see if I can figure out anything.

```
"tls": {
  "automation": {
    "policies": [
      {
        "subjects": [
          "SUBDOMAIN.example.com"
        ],
        "issuer": {
          "challenges": {
            "dns": {
              "provider": {
                "api_token": "TOKEN_HERE",
                "name": "cloudflare"
              },
              "resolvers": [
                "8.8.8.8"
              ]
            }
          },
          "module": "acme"
        }
      }
    ]
  }
}
```

**Comment by alexyao2015** [comment] 2020-10-09 00:12
@mholt 
I've just simply decided to fix my dns configuration now that I understand what the problem is. 

For future users, my issue was related to adding subdomain.example.com as a primary zone instead of using example.com as the primary zone in my dns configuration. It appears the plugin uses the primary zone when sending data to the api. Changing that configuration will allow split-brain dns to function properly with this plugin.

**Comment by mholt** [comment] 2020-10-09 18:30
Thanks for the follow-up. Indeed, CertMagic's DNS utilities will look up the primary zone. Is there a better way to figure this out automatically? Here's the code: https://github.com/caddyserver/certmagic/blob/master/dnsutil.go

Improvements welcomed!

**Comment by alexyao2015** [comment] 2020-10-09 19:13
Is there a reason why it is not able to just able to simply split the string by `.` and get the last two values? Maybe I might be missing something, but I assume there are no root domains with two `.`.

**Comment by mholt** [comment] 2020-10-09 19:15
@alexyao2015 You mean like `.co.uk`?

**Comment by alexyao2015** [comment] 2020-12-20 19:53
@mholt 
I appear to be running into this same issue again... I now have my primary zone for my split DNS server as example.com, meaning that I have to replicate my entire DNS configuration in both my internal DNS and Cloudflare. This wouldn't an issue, however it seems that the plugin also uses the internal DNS server to check if the TXT record has been propagated, which it will never find because the internal DNS is separate from Cloudflare.

The only solution I can think of for this would be specify a different, external DNS resolver to be used for certificate issuance. It would still require the internal DNS to be used for the rest of the Caddy configuration, so simply changing the global resolver would not be of help. 

Is there any chance you would consider this feature or does this feature already exist?

**Comment by mholt** [comment] 2020-12-20 20:31
@alexyao2015 You can customize the resolvers here:

- JSON ("resolvers" field): https://caddyserver.com/docs/json/apps/tls/automation/policies/issuer/acme/#challenges/dns/resolvers

- Or, with the Caddyfile: https://caddyserver.com/docs/caddyfile/directives/tls#acme

**Closed** 2020-12-23 19:27 UTC

**Comment by shahidcodes** [comment] 2023-02-26 07:19
is it possible to define the DNS directive in global options? it's very inconvenient to define it at every domain level

**Comment by mholt** [comment] 2023-02-27 18:06
Not yet; the JSON config probably gives you greater flexibility there. But I think global DNS resolver settings has been discussed before.
