### ISSUE TITLE
Dependencies with caddy 2.7.3 should be 2.7.2

### ISSUE THREAD

**Issue by devMls** [caddy-dns/cloudflare#60] opened 2023-08-09 22:13 UTC
Hi, i have this problem on build:

go: github.com/caddy-dns/cloudflare@upgrade (v0.0.0-20230807034102-74f004e1c1ab) requires github.com/caddyserver/caddy/v2@v2.7.3, not github.com/caddyserver/caddy/v2@v2.7.2

but in caddy docker hub i only find 2.7.2, maybe because caddy 2.7.2 not exist yet

https://hub.docker.com/_/caddy

**Comment by mholt** [comment] 2023-08-09 22:46
Duplicate of #59.

**Closed by mholt** 2023-08-09 22:46 UTC
